config/routes.rb
Rails.application.routes.draw do

  resources :users, only:[:index, :new, :create, :show, :edit, :destroy, :update]
  resources :sessions, only: [:create, :new, :destroy]
  resources :projects do
    resources :tasks do
      resources :comments, only: [:create, :destroy, :update, :edit]
      resources :hours
    end
  end


  root :to => "projects#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :role

  validates :user_id, presence: true
  validates :role_id, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task

  validates :user_id, presence:true
  validates :task_id, presence:true
  validates :content, presence:true
end

app/models/hour.rb
class Hour < ApplicationRecord
  belongs_to :task
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks

end

app/models/role.rb
class Role < ApplicationRecord
  has_many :assignments
  has_many :users, through: :assignments

  validates :name, presence: true , uniqueness: true

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: "author_id"
  belongs_to :assign, class_name: "User", foreign_key: "assign_id"
  belongs_to :parent, class_name: "Task", foreign_key: "parent_id", optional:true
  belongs_to :project, class_name: "Project", foreign_key: "project_id"
  has_many :sub_tasks, class_name: "Task", foreign_key: "parent_id", dependent: :destroy
  has_many :hours, dependent: :destroy
  has_many :comments, dependent: :destroy


  validates :author_id, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :assign, presence: true


  enum status: [:open ,:cancelled, :in_progress, :completed, :waiting ]

end

app/models/user.rb
class User < ApplicationRecord
  has_many :assignments
  has_many :roles, through: :assignments
  has_many :comments

  has_many :tasks
  has_many :assign_tasks, class_name: "Task", foreign_key: "assign_id", dependent: :nullify

  before_save { self.email = email.downcase }

  has_secure_password
  validates :password, :on => :create, :on =>:update, presence: true, length: { minimum: 6 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, length: {maximum: 225},
            format:{ with: VALID_EMAIL_REGEX }


  def is_admin?
    return self.roles.map{|role| role.name }.include?("admin")
  end

  def is_role?(role_name)
    return self.roles.map{|role| role.name }.include?(role_name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def set_current_user
    if session[:user_id].present?
      @current_user=User.find(session[:user_id])
    else
      redirect_to new_session_path
    end
  end


end

app/controllers/comments_controller.rb
class CommentsController < ActionController::Base
  before_action :set_comment, only: [:destroy,:update]

  def create
    content= params[:comment][:content]
    taskId=params[:task_id]
    @comment= Comment.create(content:content, task_id: taskId, user_id: session[:user_id])

    if @comment.present?
      redirect_to project_task_path(params[:project_id],@comment.task)
    end
  end

  def update
    @comment.update(comment_params)
      flash[:notice] = "Comment modified!!!!!"
    redirect_to project_task_path(params[:project_id],@comment.task)
  end

  def destroy
    @comment.destroy()
    redirect_to project_task_path(params[:project_id],params[:task_id])
  end

  private

  def set_comment
    @comment=Comment.find(params[:id].to_i)
  end
  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/hours_controller.rb
class HoursController < ApplicationController
  def create
    taskId=params[:task_id]
    projectId=params[:project_id]
    @hour= Hour.new(hour_params)
    @hour.task_id= taskId

    if @hour.save
      redirect_to project_tasks_path(projectId,taskId)
    end
  end

  private

  def hour_params
    params.require(:hour).permit(:description,:time_add )
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_current_user

  def index
   @projects= Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to project_path(@project)
    else
      render 'new'
    end
  end

  def show
    set_project
  end


  private

  def set_project
    @project= Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_current_user, only: [:destroy]

  def create
    user= User.find_by_email(params[:session][:email])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to projects_path

    else
      flash[:notice] = "Wrong credential!!!"
      render 'new'

    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_current_user
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  def index
    @tasks= Task.where(parent_id: nil,project_id:params[:project_id])

  end

  def show

    if @task.parent_id.nil?
      subtasks_hour=@task.sub_tasks.map {|subtask| subtask.hours}
      total_sub=subtasks_hour.flatten.map{|hour| hour.time_add}.sum
      total_present=@task.hours.map {|time|time.time_add}.sum
      @total=total_sub+total_present

    else
      total=@task.hours.map {|time|time.time_add}
      @total= total.sum
    end

  end


  def new
    @task = Task.new(parent_id: params[:parent_id])
    @project= Project.find(params[:project_id])

  end

  def create

    @task = Task.new(task_params)
    @task.author = @current_user
    @task.assign_id= task_params[:assign_id]
    @task.project_id= params[:project_id].to_i
    if params[:parent_id].present?
      @task.parent_id= params.require(:parent_id)
    end
    if @task.save
      redirect_to project_tasks_path(@task.project_id)
    else
      render 'new'
    end
  end

  def edit
    @project= Project.find(params[:project_id])

  end

  def update
    @task.update(task_params)
    redirect_to project_tasks_path
  end

  def destroy
    @task.destroy
    redirect_to project_tasks_path
  end

  private
  def set_page
    @task= Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :assign_id, :status, :project_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_current_user, except: [:new, :create]
  before_action :set_page, only: [:show,:edit,:update]

  def index
    @users= User.all
  end

  def new
    @user = User.new
  end

  def show

  end

  def create
    @user = User.new(user_params)

    if @user.save
      @user.assignments.create(role: Role.where(name:"user").first)
      redirect_to new_session_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update

    if @user.update(user_params)
    @user.assignments.where(user_id:@user.id).destroy_all
      params[:role].each do |role|
      @user.assignments.create(role: Role.where(name:role).first)
      end
    redirect_to users_path
    else
      render 'edit'
    end


  end


  private

  def set_page
    @user= User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/controllername_helper.rb
module ControllernameHelper
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/projects/index.html.erb
<tbody>

<% @projects.each do |project| %>
<ul>
    <tr role="row" class="odd">
      <td class="sorting_1"> <%= project.id %> </td>
      <td> <%= link_to(project.title, project_path(project))%> </td>
    </tr>
</ul>
<%end %>

</tbody>


<p> <%= link_to("Create a Project", new_project_path) %> </p>

app/views/projects/new.html.erb
<%= form_for(@project)do |f| %>

    <div class="name">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <%= f.submit "Submit" %>
<% end %>

app/views/projects/show.html.erb
<h1> project name: <%= @project.title %></h1>

<p><%= link_to("all task for this project", project_tasks_path(@project))%></p>

app/views/tasks/_form.html.erb
    <div class="name">
      <%= f.label :name %>
      <%= f.text_field :name %>

    </div>

    <div class="name">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>

    <div class="control-group">
      <%= f.label "Assign to", class:'control-label' %>
      <div class="controls">

        <%=f.select(:assign_id, options_for_select(
            User.all.map do |u|
              [u.name, u.id]
            end)) %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label "Status", class:'control-label' %>
      <div class="controls">
        <%=f.select(:status, options_for_select(Task.statuses.map { |status| [status.first, status.first]}))  %>
      </div>
    </div>



    <%= hidden_field_tag(:parent_id, params[:parent_id]) %>

    <%= f.submit "Submit" %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= form_for [@project,@task], :url => { :action => "update" } do |form| %>
    <%= render partial: 'form', locals: { f: form } %>
<%end%>

app/views/tasks/index.html.erb
<div class="content-wrapper">
  <div class="container-fluid">
    <div class="card mb-3">
      <div class="card-header">
        <i class="fa fa-table"></i> List of tasks
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <div id="dataTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4">
            <div class="row">
              <div class="col-sm-12 col-md-6">
              <div class="dataTables_length" id="dataTable_length">
                <label>Show
                  <h1>
                    Project name:
                    <%= Project.find(params[:project_id]).title  %>
                  </h1>
                  <select name="dataTable_length" aria-controls="dataTable" class="form-control form-control-sm">
                    <option value="10">10</option>
                    <option value="25">25</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                  </select> entries
                </label>
              </div>
              </div>
              <div class="col-sm-12 col-md-6">
                <div id="dataTable_filter" class="dataTables_filter">
                  <label>Search:<input type="search" class="form-control form-control-sm" placeholder="" aria-controls="dataTable">
                  </label>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12">
                <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
            <thead>
            <tr role="row"><th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Task id: activate to sort column descending" aria-sort="ascending" style="width: 257px;">Task id</th>
              <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Task name: activate to sort column ascending" style="width: 410px;">Task name</th>
              <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Author: activate to sort column ascending" style="width: 410px;">Author</th>
              <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Assign to: activate to sort column ascending" style="width: 410px;">Assign to</th>
              <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Description: activate to sort column ascending" style="width: 197px;">Description</th>
              <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Task Status: activate to sort column ascending" style="width: 410px;">Task Status</th>
              <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Start date: activate to sort column ascending" style="width: 177px;">Start date</th>
              <th class="link" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Link to task " style="width: 177px;">Link to task</th>

            </tr>
            </thead>
            <tfoot>
              <th rowspan="1" colspan="1">Task id</th>
              <th rowspan="1" colspan="1">Task name</th>
              <th rowspan="1" colspan="1">Author</th>
              <th rowspan="1" colspan="1">Assign to</th>
              <th rowspan="1" colspan="1">Description</th>
              <th rowspan="1" colspan="1">Task Status</th>
              <th rowspan="1" colspan="1">Start date</th>
              <th rowspan="1" colspan="1">Link to task</th>

            </tfoot>
            <tbody>

            <% @tasks.each do |task| %>


                <tr role="row" class="odd">

                  <td class="sorting_1"> <%= task.id %> </td>
                  <td><%= task.name %></td>
                  <td><%= link_to(task.author.name,user_path(task.author)) %></td>
                  <td><%= task.assign.name %></td>
                  <td><%= truncate(task.description,length: 30) %></td>
                  <td><%= task.status %></td>
                  <td><%= task.created_at%> </td>
                  <td>
                    <%= link_to("Link to task", project_task_path(params[:project_id],task)) %>
                  </td>

                </tr>

            <%end %>

            </tbody>
          </table>
          </div>
          </div><div class="row"><div class="col-sm-12 col-md-5">
            <div class="dataTables_info" id="dataTable_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div>
          </div><div class="col-sm-12 col-md-7">
            <div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate">
              <ul class="pagination"><li class="paginate_button page-item previous disabled" id="dataTable_previous">
                <a href="#" aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a>
              </li><li class="paginate_button page-item active">
                <a href="#" aria-controls="dataTable" data-dt-idx="1" tabindex="0" class="page-link">1</a>
              </li><li class="paginate_button page-item ">
                <a href="#" aria-controls="dataTable" data-dt-idx="2" tabindex="0" class="page-link">2</a>
              </li>
                <li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="3" tabindex="0" class="page-link">3</a></li>
                <li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="4" tabindex="0" class="page-link">4</a></li>
                <li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="5" tabindex="0" class="page-link">5</a></li>
                <li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="6" tabindex="0" class="page-link">6</a></li>
                <li class="paginate_button page-item next" id="dataTable_next"><a href="#" aria-controls="dataTable" data-dt-idx="7" tabindex="0" class="page-link">Next</a></li>
              </ul>
            </div>
          </div>
          </div>
          </div>
        </div>
      </div>
      <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
    </div>



    <%= link_to("Create a new task", new_project_task_path(params[:project_id])) %>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>create!</h1>

<%= form_for [@project,@task], :url => { :action => "create" } do |form| %>
    <%= render partial: 'form', locals: { f: form } %>
<%end%>

app/views/tasks/show.html.erb
<h1> task name: <%= @task.name %></h1>

<p> task description: <%= @task.description %> </p>

<p> task status: <%= @task.status %> </p>

<p> assign to: <%=  User.find(@task.assign).name %> </p>

<ul>
  <%@task.comments.each do |comment| %>
    <li><%= comment.content %></li>
      <p><%= comment.user.name %>, <%= comment.created_at%> </p>
      <% if @current_user.is_admin?%>
        <%= link_to("Delete comment", project_task_comment_path(params[:project_id],task_id: @task.id, id: comment.id) ,method: "delete") %>
        <br>

          <div class="comment">
          <%= form_for(comment,url: project_task_comment_path(params[:project_id],@task,comment.id))do |f| %>
              <div class="name">
                <%= f.label :Modify_comments %>
                <%= f.text_area :content %>
              </div>
              <%= f.submit "Submit" %>
          <% end %>
            <% if flash[:notice] %>
                <div class="notice"><%= flash[:notice] %></div>
            <% end %>
          </div>

        <% end %>
  <% end %>
</ul>

<%= form_for("comment", url: project_task_comments_path(params[:project_id],@task)) do |f| %>
    <div class="name">
      <%= f.label :comments %>
      <%= f.text_area :content %>

    </div>
    <%= f.submit "Submit" %>
<% end %>

<ul>
  <%@task.sub_tasks.each do |subtask| %>
    <li> <%= link_to(subtask.name, project_task_path(params[:project_id],subtask.id))%> </li>
  <% end %>
</ul>

<p> <%= link_to("Create a subtask", new_project_task_path(params[:project_id],parent_id:@task.id )) %> </p>

<% if @current_user.is_admin?%>
<p> <%= link_to("Delete task", project_task_path(params[:project_id]), method: "delete") %> </p>
<% end %>

<p><%= link_to("Edit", edit_project_task_path(params[:project_id],@task))%></p>

<p> <%= link_to("link to all task", project_tasks_path(params[:project_id])) %> </p>


<%= form_for("hour", url: project_task_hours_path(params[:project_id],@task)) do |f| %>
    <div class="name">
      <%= f.label :Add_description_for_hour_spent %>
      <%= f.text_area :description %>
    </div>

    <div class="name">
      <%= f.label :Add_hours %>
      <%= f.number_field :time_add %>
    </div>


    <%= f.submit "Submit" %>
<% end %>


  <p>Hours worked on this task:<%=@total%></p>

app/views/users/_form.html.erb
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user)do |f| %>

          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control'%>

          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>

          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>

          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>

          <% if  @current_user.present? && @current_user.roles.first.name== "admin"%>

            <div class="name">
              <b>Role</b><br />

              <% Role.all.each do |role| %>
                  <%= check_box_tag("role[]",role.name,@user.is_role?(role.name))%>
                  <%=role.name%> <br>
              <% end %>
            </div>

          <% end%>

        <div class="errors">
        <% if @user.errors.any?%>
            <h2>Errors: </h2>
            <ul>
              <% @user.errors.full_messages.each do |message|%>
                  <li><%= message %> </li>
              <% end%>
            </ul>
        <%end%>
        </div>

        <%= f.submit "Submit", class: "btn btn-primary" %>

    <% end %>
  </div>

app/views/users/edit.html.erb
<<%= render 'form' %>

app/views/users/index.html.erb
<table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
  <thead>
  <tr role="row"><th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="User id: activate to sort column descending" aria-sort="ascending" style="width: 257px;">User id</th>
    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="User name: activate to sort column ascending" style="width: 410px;">User name</th>
    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Role: activate to sort column ascending" style="width: 410px;">Role</th>


  </tr>
  </thead>
  <tfoot>
  <th rowspan="1" colspan="1">User id</th>
  <th rowspan="1" colspan="1">User Name</th>
  <th rowspan="1" colspan="1">Role</th>
  </tfoot>
  <tbody>

  <% @users.each do |user| %>

      <tr role="row" class="odd">

        <td class="sorting_1"> <%= user.id %> </td>
        <td>
          <%=link_to(user.name.capitalize, user_path(user))%>
        <td>
        <%= user.roles.map{|role| role.name.capitalize}.join(", ") %>
        </td>

      </tr>
  <% end %>

  </tbody>
</table>

app/views/users/new.html.erb
<div class="row">
  <h1 align="center">Signup!</h1>
<%= render 'form' %>

</div>

app/views/users/show.html.erb
<div class="name">
  <p><%= @user.name%></p>

  <%= @user.roles.map{|role| role.name.capitalize}.join(", ") %>

    <% if @current_user.is_admin? %>
      <p>
      <%= link_to("Edit user", edit_user_path(@user)) %>
      </p>
    <% end %>

</div>